mysql:
  m: root:root@tcp(localhost:3307)/management
  s: root:root@tcp(localhost:3307)/management

rabbit:
  host: amqp://youqian:12aimiao@localhost:5672/

redis:
  host: localhost:6379

vehicle_config:
  host: http://zhhq-test240.zkfc.cn/api/park_smart/web/device/list