package utils

const AMMETER_SUPERVISOR = 1
const AMMETER_MANAGER = 2

const AMMETER_DATA_TYPE_CONSUMPTION = 1
const AMMETER_DATA_TYPE_LEAKAGE = 2
const AMMETER_DATA_TYPE_CURRENT = 3
const AMMETER_DATA_TYPE_VOLTAGE = 4
const AMMETER_DATA_TYPE_TEMPERATURE = 5
